[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.16.5",
    "asyncpg>=0.30.0",
    "bcrypt>=4.3.0",
    "dishka>=1.7.1",
    "fastapi[standart]>=0.117.1",
    "gunicorn>=23.0.0",
    "joblib>=1.5.2",
    "numpy>=2.3.3",
    "pandas>=2.3.3",
    "pyjwt[crypto]>=2.10.1",
    "python-dotenv>=1.1.1",
    "scikit-learn>=1.7.2",
    "sqlalchemy>=2.0.43",
    "torch>=2.8.0",
    "transformers>=4.56.2",
    "uvicorn>=0.36.0",
]
[dependency-groups]
dev = [
    "ruff>=0.13.1",
]
