[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dishka>=1.7.1",
    "fastapi[standart]>=0.117.1",
    "gunicorn>=23.0.0",
    "uvicorn>=0.36.0",
]
[dependency-groups]
dev = [
    "ruff>=0.13.1",
]
