"""empty message

Revision ID: e4a31d68ad92
Revises:
Create Date: 2025-09-30 01:53:52.354714

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e4a31d68ad92"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reviews",
        sa.Column("review_id", sa.UUID(), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("sentiment", sa.String(length=12), nullable=False),
        sa.Column("created_at", sa.Date(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("review_id", name=op.f("pk_reviews")),
    )
    op.create_table(
        "topics",
        sa.Column("topic_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("topic_id", name=op.f("pk_topics")),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=40), nullable=False),
        sa.Column("password", sa.LargeBinary(), nullable=False),
        sa.Column("role", sa.Enum("user", "admin", native_enum=False), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "topic_review",
        sa.Column("topic_id", sa.UUID(), nullable=False),
        sa.Column("review_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["reviews.review_id"],
            name=op.f("fk_topic_review_review_id_reviews"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.topic_id"],
            name=op.f("fk_topic_review_topic_id_topics"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("topic_id", "review_id", name=op.f("pk_topic_review")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("topic_review")
    op.drop_table("users")
    op.drop_table("topics")
    op.drop_table("reviews")
    # ### end Alembic commands ###
